### PR TITLE
Schema changes, OpenMS & CADDSuite using the same codebase

### PR DESCRIPTION
**Pull request by chahuistle**

### CODE REVIEW

**Comment by bgruening** [comment]
Wow great work! 
Have you checked if the resulting OpenMS wrappers are identical with the old ones?

**Comment by chahuistle** [comment]
Yes, so far, they are... I am adding a tiny feature that will help OpenMS,
but in the next days, I think I will let you know how to run the tool to
generate the wrappers.

**Comment by bgruening** [comment]
Thanks a lot!

xref: https://github.com/bgruening/galaxytools/tree/master/tools/openms

**Comment by bgruening** [comment]
@chahuistle correct me if I'm wrong but this library is for developers and this feature is need by developers, simply because Galaxy offers more features than CTD and we need to tweak the tools for a foreseeable future. Sure I can write a script to correct this, I can also fork this repository. 
This project should maybe think about who are the users and how to treat them. I think @TorHou and me did a lot of work here and we are probably one of your main users.
This one here for example is really sad: https://github.com/WorkflowConversion/CTD2Galaxy/issues/3#issuecomment-151305803

**Comment by chahuistle** [comment]
Well I guess I never thought of it like that, but you are absolutely right! I'm sorry.

A project that complicates people's lifes is probably not a good project. The only thing that I think we should agree on is that there should not be OpenMS-specific code in CTD2Galaxy to keep it as generic as possible.

@bgruening @TorHou 
Do you guys have a branch based on my latest commits? I think that it'd be hell to do a pull request (it'll be conflicts all over). If not, then I would go ahead and start a separate branch and generate attributes in alphabetical order.

**Pull request merged**
